spring:
  application:
    name: api-gateway
server:
  port: 5555
security:
  user:
    name: admin
    password: admin

---
eureka:
  instance:
#    prefer-ip-address: true
    hostname: api.ymu.com #域名
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
       defaultZone: http://eureka.ymu.com:2221/eureka/ #注册发现服务

---
#message
spring:
  messages:
    basename: i18n/messages

---
##从配置中心读取配置
#spring:
#  cloud:
#    config:
#      name: api-gateway
#      profile: dev
#      label: master
#      fail-fast: true
#      discovery:
#        enabled: true
#        service-id: ymu-config-server
#      username: admin
#      password: 123456

---
#开启重试机制
#参考：http://blog.didispace.com/spring-cloud-zuul-retry-detail/
zuul:
  retryable: true #是否开启重试功能
ribbon:
  MaxAutoRetries: 3 #同一个Server重试的次数(除去首次)
  MaxAutoRetriesNextServer: 0 #切换相同Server的次数

---
#饥饿加载
zuul:
  ribbon:
    eager-load:
      enabled: true

---
#禁用过滤器
zuul:
  SendErrorFilter:
    error:
      disable: true

---
#redis
spring:
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: localhost # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
    timeout: 10 # 连接超时时间（毫秒）

---
#配置路由
zuul:
  routes:
    api-common:
      path: /common/**
      stripPrefix: true
      service-id: service-common #服务service-common
    api-b:
      path: /file/**
      stripPrefix: true
      #服务service-fileclient
      service-id: service-fileclient
  # 忽略所有的默认路由，让所有路由配置均维护在配置文件中，以达到网关启动的时候就默认初始化好各个路由转发的负载均衡对象。
  ignored-services: '*'